## Tensor Transposition
![Tensor Transposition](./images/tensor-transpositions.png "Tensor Transposition")

In [29]:
import torch
import numpy as np
import tensorflow as tf

In [30]:
x = np.array([[1,2], [2,3], [3,4]])
x

array([[1, 2],
       [2, 3],
       [3, 4]])

In [31]:
x.T

array([[1, 2, 3],
       [2, 3, 4]])

In [32]:
x_tf = tf.Variable([[1,2], [2,3], [3,4]])
tf.transpose(x_tf)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [2, 3, 4]], dtype=int32)>

In [33]:
x_pt = torch.tensor([[1,2], [2,3], [3,4]])
x_pt

tensor([[1, 2],
        [2, 3],
        [3, 4]])

In [34]:
x_pt.T

tensor([[1, 2, 3],
        [2, 3, 4]])

## Basic tensor arithmetic
Adding or multiplying a tensor with a scaler applies operations to all element and tensor's shape is retained

In [35]:
x

array([[1, 2],
       [2, 3],
       [3, 4]])

In [36]:
x+2

array([[3, 4],
       [4, 5],
       [5, 6]])

In [37]:
x*2

array([[2, 4],
       [4, 6],
       [6, 8]])

In [38]:
x*2+2

array([[ 4,  6],
       [ 6,  8],
       [ 8, 10]])

In [39]:
torch.add(torch.mul(x_pt, 2), 2)

tensor([[ 4,  6],
        [ 6,  8],
        [ 8, 10]])

In [40]:
tf.add(tf.multiply(x_tf, 2), 2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 4,  6],
       [ 6,  8],
       [ 8, 10]], dtype=int32)>

In [41]:
x_tf*2+2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 4,  6],
       [ 6,  8],
       [ 8, 10]], dtype=int32)>

## Hadamard Product
![Hadamard Product](./images/hadamard-product.png "Hadamard Product")

In [42]:
x

array([[1, 2],
       [2, 3],
       [3, 4]])

In [43]:
x1 = x + 2
x1

array([[3, 4],
       [4, 5],
       [5, 6]])

In [44]:
x + x1

array([[ 4,  6],
       [ 6,  8],
       [ 8, 10]])

In [45]:
x * x1

array([[ 3,  8],
       [ 8, 15],
       [15, 24]])

## Reduction
![Reduction](./images/reduction.png "Reduction")

In [51]:
x

array([[1, 2],
       [2, 3],
       [3, 4]])

In [46]:
x.sum()

15

In [49]:
torch.sum(x_pt)

tensor(15)

In [48]:
tf.reduce_sum(x_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=15>

In [54]:
# sum along an axis
torch.sum(x_pt, 0)

tensor([6, 9])

In [57]:
torch.sum(x_pt, 1)

tensor([3, 5, 7])

In [55]:
tf.reduce_sum(x_pt, 0)

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([6, 9])>

In [56]:
tf.reduce_sum(x_pt, 1)

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([3, 5, 7])>

![Other tensor operation](./images/reduction-2.png "Other tensor operation")