## Tensor Transposition
![Tensor Transposition](./images/tensor-transpositions.png "Tensor Transposition")

In [2]:
import torch
import numpy as np
import tensorflow as tf

In [3]:
x = np.array([[1,2], [2,3], [4,5]])
x

array([[1, 2],
       [2, 3],
       [4, 5]])

In [4]:
x.T

array([[1, 2, 4],
       [2, 3, 5]])

In [17]:
x_tf = tf.Variable([[1,2], [2,3], [4,5]])
tf.transpose(x_tf)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 4],
       [2, 3, 5]], dtype=int32)>

In [8]:
x_pt = torch.tensor([[1,2], [2,3], [3,4]])
x_pt

tensor([[1, 2],
        [2, 3],
        [3, 4]])

In [9]:
x_pt.T

tensor([[1, 2, 3],
        [2, 3, 4]])

## Basic tensor arithmetic
Adding or multiplying a tensor with a scaler applies operations to all element and tensor's shape is retained

In [12]:
x

array([[1, 2],
       [2, 3],
       [4, 5]])

In [10]:
x+2

array([[3, 4],
       [4, 5],
       [6, 7]])

In [11]:
x*2

array([[ 2,  4],
       [ 4,  6],
       [ 8, 10]])

In [13]:
x*2+2

array([[ 4,  6],
       [ 6,  8],
       [10, 12]])

In [14]:
torch.add(torch.mul(x_pt, 2), 2)

tensor([[ 4,  6],
        [ 6,  8],
        [ 8, 10]])

In [19]:
tf.add(tf.multiply(x_tf, 2), 2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 4,  6],
       [ 6,  8],
       [10, 12]], dtype=int32)>

In [20]:
x_tf*2+2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 4,  6],
       [ 6,  8],
       [10, 12]], dtype=int32)>

## Hadamard Product
![Hadamard Product](./images/hadamard-product.png "Hadamard Product")

In [21]:
x

array([[1, 2],
       [2, 3],
       [4, 5]])

In [22]:
x1 = x + 2
x1

array([[3, 4],
       [4, 5],
       [6, 7]])

In [23]:
x + x1

array([[ 4,  6],
       [ 6,  8],
       [10, 12]])

In [25]:
x * x1

array([[ 3,  8],
       [ 8, 15],
       [24, 35]])