## Tensor Transposition
![Tensor Transposition](./images/tensor-transpositions.png "Tensor Transposition")

In [2]:
import torch
import numpy as np
import tensorflow as tf

In [3]:
x = np.array([[1,2], [2,3], [4,5]])
x

array([[1, 2],
       [2, 3],
       [4, 5]])

In [4]:
x.T

array([[1, 2, 4],
       [2, 3, 5]])

In [6]:
tf.transpose(x)

<tf.Tensor: shape=(2, 3), dtype=int64, numpy=
array([[1, 2, 4],
       [2, 3, 5]])>

In [8]:
x_pt = torch.tensor([[1,2], [2,3], [3,4]])
x_pt

tensor([[1, 2],
        [2, 3],
        [3, 4]])

In [9]:
x_pt.T

tensor([[1, 2, 3],
        [2, 3, 4]])